version: '3'
services:
  mongo:
    env_file: .env
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE= ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT-27017}:${MONGODB_PORT-27017}
    volumes:
      - mongodb_data_container:/data/db

  rabbitmq:
    env_file: .env
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
volumes:
  mongodb_data_container:
  rabbitmq_data:
